name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8 mypy
    
    - name: Lint
      run: |
        black --check agents/ tests/
        flake8 agents/ tests/ --max-line-length=100
    
    - name: Type check
      run: mypy agents/ --ignore-missing-imports
    
    - name: Test
      run: pytest tests/ -v --asyncio-mode=auto
    
    - name: Generate test report
      if: always()
      run: |
        pytest tests/ --junitxml=test-results.xml --cov=agents --cov-report=xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and test Docker image
      run: |
        docker build -t anomaly-agent:test -f docker/Dockerfile .
        docker run --rm anomaly-agent:test python -m pytest tests/
    
    - name: Login to Registry
      if: success()
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Push image
      if: success()
      run: |
        docker tag anomaly-agent:test ghcr.io/${{ github.repository }}:latest
        docker tag anomaly-agent:test ghcr.io/${{ github.repository }}:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}:latest
        docker push ghcr.io/${{ github.repository }}:${{ github.sha }}